// @ts-check
// pnpm status  ->  rewrites the item tables in STATUS.md from catalog/catalog.json, so
// the table can never drift from the catalog. Everything outside the markers is kept.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = path.join(import.meta.dirname, "..");
const statusFile = path.join(root, "STATUS.md");
const START = "<!-- items:start -->";
const END = "<!-- items:end -->";

/** @typedef {{ id: string, kind: string, name: string, order: number, prompt: string, state: string, category?: string | null, description?: string | null, label?: string | null }} Entry */

/** @type {Entry[]} */
const catalog = JSON.parse(readFileSync(path.join(root, "catalog", "catalog.json"), "utf8"));

const GROUPS = [
  { kind: "lib", title: "Libraries", note: (/** @type {Entry} */ e) => e.category ?? "" },
  { kind: "site", title: "Sites", note: (/** @type {Entry} */ e) => e.label ?? "" },
  { kind: "lab", title: "Lab seeds", note: (/** @type {Entry} */ e) => e.description ?? "" },
];

const sections = GROUPS.map(({ kind, title, note }) => {
  const items = catalog.filter((e) => e.kind === kind).sort((a, b) => a.order - b.order);
  const rows = items.map((e) => `| ${e.id} | ${e.name} | ${e.prompt} | ${e.state} | ${note(e)} |`);
  return [
    `### ${title} (${items.length})`,
    "",
    "| Id | Name | Gate | State | Note |",
    "| --- | --- | --- | --- | --- |",
    ...rows,
  ].join("\n");
});

const states = catalog.reduce((acc, e) => acc.set(e.state, (acc.get(e.state) ?? 0) + 1), new Map());
const summary = [...states].map(([state, n]) => `${n} ${state}`).join(", ");
const block = `${START}\n_${catalog.length} items: ${summary}. Generated by \`pnpm status\`; edit the catalog, not this table._\n\n${sections.join("\n\n")}\n${END}`;

const current = readFileSync(statusFile, "utf8");
const from = current.indexOf(START);
const to = current.indexOf(END);
if (from < 0 || to < 0) throw new Error("STATUS.md is missing the items markers");
writeFileSync(statusFile, current.slice(0, from) + block + current.slice(to + END.length));
console.log(`STATUS.md updated: ${catalog.length} items (${summary}).`);
